Added first test file
AnnaLangner/pysandbox pull request #24
Opened 2020-07-01 18:52 UTC by AnnaLangner

2020-07-01 19:41 UTC, klangner requested changes

2020-07-01 19:41 UTC, klangner commented on script/test_1.py
> +driver = webdriver.Chrome(executable_path="D:\Programowanie\chromedriver_win32\chromedriver.exe")
It is better to put this executable in folder inside this project (e.g. `bin/`) and add this folder to .gitignore (So the file will not end up in the repo).

2020-07-01 19:51 UTC, klangner requested changes
Does it work?

2020-07-02 07:43 UTC, AnnaLangner commented
It doesn't work.
I have an error:
```
Traceback (most recent call last):
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Usersl\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Nie można odnaleźć określonego pliku

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_1.py", line 5, in <module>
    driver = webdriver.Chrome(executable_path="bin\chromedriver_win32\chromedriver.exe")
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
```
but I added it to path.

2020-07-02 11:32 UTC, klangner approved these changes

2020-07-02 11:48 UTC, merged