Task 3. Create min.py script
AnnaLangner/pysandbox pull request #5
Opened 2020-06-17 12:57 UTC by AnnaLangner

2020-06-17 13:32 UTC, klangner requested changes
The parameters should be provided during program run as command line parameters

2020-06-17 13:34 UTC, klangner requested changes

2020-06-17 13:34 UTC, klangner commented on script/min.py
> +if float(x) > float(y) :
What about situation when x == y? Something should be printed.

2020-06-17 20:38 UTC, AnnaLangner commented
changes have been made

2020-06-17 20:45 UTC, klangner requested changes

2020-06-17 20:45 UTC, klangner commented on script/min.py
> +parser = argparse.ArgumentParser()
Please add 2 empty lines after imports.

2020-06-17 20:45 UTC, klangner commented on script/min.py
> +if float(args.num1) > float(args.num2) :
Please remove space before ':' (in all lines)

2020-06-17 20:45 UTC, klangner commented on script/min.py
> +  print("Numbers are equal")
Pleas add one empty line at the end of the file

2020-06-18 07:39 UTC, AnnaLangner commented
changes have been made

2020-06-18 07:54 UTC, merged

2020-06-18 07:54 UTC, klangner commented
Ok. Good job.